version: '3.1' 
services:
    eureka-serviceregistry:
        build: ./netflix-eureka-naming-server
        image: eureka-naming-server:0.0.2
        ports:
            - "8761:8761"
        tty:
            true
        restart:
            unless-stopped
         
    stack-push-pop-service:               
        build:  ./stack-push-pop-service
        image: stack-push-pop-service:0.0.1
        ports:
            - "8080:8080"
        environment:
            - REGISTRY_HOST=eureka-serviceregistry
        depends_on:
            - postgresqldb
        tty:
            true
        restart:
            unless-stopped
    postgresqldb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            
    StackImplementation-service:
        build: ./StackImplementation-service
        image: stack-implementation-service:0.0.1
        ports:
            - "8092:8092"
        environment:
            - REGISTRY_HOST=eureka-serviceregistry
        tty:
            true
        restart:
            unless-stopped
            